"""add ai outfit history

Revision ID: ac59bf3daa4c
Revises: 
Create Date: 2026-05-11 15:22:01.951401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac59bf3daa4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('password_reset_codes_user_id_fkey'), 'password_reset_codes', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_profiles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('user_profiles_user_id_fkey'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('wardrobe_items', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('wardrobe_items', sa.Column('temperature_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('wardrobe_items', sa.Column('usage', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('wardrobe_items', sa.Column('temperature_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('wardrobe_items', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_user_id_fkey'), 'user_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_profiles', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'password_reset_codes', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_codes_user_id_fkey'), 'password_reset_codes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
