services:
  db:
    image: postgres:16
    container_name: smartoutfit_db
    environment:
      POSTGRES_DB: smartoutfit
      POSTGRES_USER: smartoutfit
      POSTGRES_PASSWORD: smartoutfit
    ports:
      - "5432:5432"
    volumes:
      - smartoutfit_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../apps/backend
    container_name: smartoutfit_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://smartoutfit:smartoutfit@db:5432/smartoutfit
    volumes:
      - ../apps/backend:/app
    command: sh -c "alembic upgrade head && python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  smartoutfit_pgdata:
  
